import fs from "fs/promises"
import openapiTS, { astToString } from "openapi-typescript"

async function generateTypes() {
  try {
    // Load the OpenAPI schema
    const schemaPath = new URL("./schema.json", import.meta.url)
    const ast = await openapiTS(schemaPath)

    // Convert AST to TypeScript string
    const types = astToString(ast)

    // scope to add more here, versioning, etc.
    const output = `
    // 🚨 This file is autogenerated by openapi-typescript. Do not edit manually.
    // generated at ${new Date().toISOString()}

    ${types}
    `

    // Write the TypeScript definitions to a file
    await fs.writeFile("./src/types/schema.ts", output)
    console.log("TypeScript definitions generated successfully.")
  } catch (error) {
    console.error("Error generating TypeScript definitions:", error)
  }
}

generateTypes()
