name: publish on github

on:
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.8.0

      - uses: actions/setup-node@v1
        with:
          node-version: 20.0.0
          cache: pnpm
          registry-url: https://npm.pkg.github.com/
          scope: "@storyprotocol"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: |
          cd packages/storykit
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
