name: publish on github on npm

on:
  push:
    branches:
      - main

jobs:
  Timestamp:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  print_version_to_publish:
    needs: [Timestamp]
    runs-on: ubuntu-latest
    outputs:
      version_to_be_published: ${{ steps.get_version_to_publish.outputs.VERSION_TO_BE_PUBLISHED }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get version to publish
        id: get_version_to_publish
        run: |
          content=$(cat packages/storykit/package.json)
          echo "VERSION_TO_BE_PUBLISHED=$(echo $content | jq -r '.version')" >> $GITHUB_OUTPUT

  fetch_latest_version:
    needs: [Timestamp]
    runs-on: ubuntu-latest
    outputs:
      LATEST_VERSION: ${{ steps.get_latest_version.outputs.LATEST_VERSION }}
    steps:
      - name: Get latest package version
        id: get_latest_version
        run: |
          LATEST_VERSION=$(npm view @story-protocol/storykit version)
          echo "Latest version of @story-protocol/storykit on NPMJS is $LATEST_VERSION"
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
  
  fail_if_version_is_same:
    needs: [print_version_to_publish, fetch_latest_version]
    runs-on: ubuntu-latest
    steps:
      - name: Fail if version is the same
        run: |
          if [ "${{ needs.fetch_latest_version.outputs.LATEST_VERSION }}" == "${{ needs.print_version_to_publish.outputs.version_to_be_published }}" ]; then
            echo "The version to be published is the same as the latest version on NPM. Exiting..."
            exit 1
          fi  

  publish-gpr:
    needs: [print_version_to_publish, fetch_latest_version, fail_if_version_is_same]
    if: needs.fetch_latest_version.outputs.LATEST_VERSION != needs.print_version_to_publish.outputs.version_to_be_published && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.8.0

      - uses: actions/setup-node@v1
        with:
          node-version: 20.0.0
          cache: pnpm
          registry-url: https://npm.pkg.github.com/
          scope: "@storyprotocol"

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
        
      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: |
          cd packages/storykit
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
