name: publish on github on npm

on:
  push:
    branches:
      - main

jobs:
  Timestamp:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.8.0

      - uses: actions/setup-node@v1
        with:
          node-version: 20.0.0
          cache: pnpm
          registry-url: https://npm.pkg.github.com/
          scope: "@storyprotocol"

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
        
      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: |
          cd packages/storykit
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
